# Generated by Django 5.2.4 on 2025-07-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(upload_to='projetos/', verbose_name='Imagem do Projeto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('destaque', models.BooleanField(default=False, help_text='Marque esta opção para exibir o projeto na seção de destaque da página inicial. Apenas os projetos marcados aparecerão no carrossel da home.', verbose_name='Projeto em Destaque')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
