# Generated by Django 5.2.4 on 2025-07-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text="Versão amigável da URL do artigo. Ex: 'como-instalar-paineis-solares' para o título 'Como Instalar Painéis Solares'. Deixe em branco para gerar automaticamente.", max_length=200, unique=True, verbose_name='Slug')),
                ('imagem', models.ImageField(upload_to='blog/', verbose_name='Imagem do Artigo')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
